### PR TITLE
Create Child_process platform API

### PR DESCRIPTION
**Pull request by jslavin-clearblade**

### CODE REVIEW

**Review by jslavin-clearblade — COMMENTED** [review]
Made minor update about options

**Comment by savfaire** [comment]
I'd like to add the following:

1. A description of what each of the functions is used for
2. An example of how to use each function
3. A description of what the uid and gid options would be used for
4. A sample response that shows the user what is returned.

I'll have to get you this information.

**Comment by jslavin-clearblade** [comment]
> I'd like to add the following:
> 
> 1. A description of what each of the functions is used for
> 2. An example of how to use each function
> 3. A description of what the uid and gid options would be used for
> 4. A sample response that shows the user what is returned.
> 
> I'll have to get you this information.

Thanks, Jim

**Review by jslavin-clearblade — COMMENTED** [review]
I removed the exec function and added more information about the execSync function.

**Review by savfaire — APPROVED** [review]

**Pull request merged**
